project4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # 増えた
from django.conf.urls.static import static  # 増えた

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('videos.urls')),
]

# 開発環境時のみ、Djangoアプリケーション側でメディアファイルを配信する
# 開発環境ならこのように書くと覚えた方がいい
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

videos/urls.py
from django.urls import path
from . import views


app_name = 'videos'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('upload/', views.CreateView.as_view(), name='upload'),
    path('play/<int:pk>/', views.PlayView.as_view(), name='play'),
]

videos/models.py
from django.db import models


class Video(models.Model):
    """動画"""

    title = models.CharField('動画タイトル', max_length=255)
    description = models.TextField('説明（空欄可)', blank=True)
    # /media_thumbnails/ファイル名
    # upload_to=はアップロードする場所を示す
    thumbnail = models.ImageField(
        'サムネイル（空欄可)', upload_to='thumbnails/', null=True, blank=True)
    # /media/uploads/2018/3/20/ファイル名
    upload = models.FileField('ファイル', upload_to='uploads/%Y/%m/%d/')
    # default=timezone.nowと違い、入力欄は表示されない、編集ができない
    created_at = models.DateTimeField('作成日', auto_now_add=True)
    # 更新されるたびにその日時が格納される
    # auto_now=Trueとは更新するたびに、ということになる、編集ができない
    updated_at = models.DateTimeField('更新日', auto_now=True)

    def __str__(self):
        return self.title

videos/forms.py
from django import forms
from .models import Video


class VideoCreateForm(forms.ModelForm):

    class Meta:
        model = Video
        fields = ('title', 'description', 'thumbnail', 'upload')
        # 少し通な書き方
        widgets = {
            'title': forms.TextInput(attrs={  # <input type="text" class="form-control"
                'class': 'form-control',
            }),
            'description': forms.Textarea(attrs={  # <textarea class="form-control"
                'class': 'form-control',
            }),
            # input type="file"の場合、form-controlではなくform-control-file
            'thumbnail': forms.ClearableFileInput(attrs={  # <input type="file" class="form-control-file"
                'class': "form-control-file",
            }),
            'upload': forms.ClearableFileInput(attrs={
                'class': "form-control-file",
            }),
        }

videos/views.py
from django.urls import reverse_lazy
from django.views import generic
from .forms import VideoCreateForm
from .models import Video


# IndexViewはビデオの一覧表示
class IndexView(generic.ListView):
    model = Video


# CreateViewはアップデートページ
class CreateView(generic.CreateView):
    model = Video
    form_class = VideoCreateForm
    success_url = reverse_lazy('videos:index')


# DetailViewは動画の再生ページ
class PlayView(generic.DetailView):
    model = Video

videos/templates/videos/base.html
{% load static %}
<!doctype html>
<html lang="ja">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!--my css：templatesと同じ-->
    <link rel="stylesheet" href="{% static 'videos/main.css' %}">

    <title>Simple Tube</title>
  </head>

  <body>
    <!-- 上部メニュー -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'videos:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'videos:upload' %}">Upload</a>
          </li>
        </ul>
      </div>
    </nav><!-- 上部メニュー終わり -->

    <div class="container">
      <div class="jumbotron">
        <h1 class="display-3">SimpleTube</h1>
        <p class="lead">シンプルな動画アップロードサービス</p>
        <hr class="my-2">
      </div>
      {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
      crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>

</html>

videos/templates/videos/video_detail.html
{% extends 'videos/base.html' %}
{% block content %}
<h1>{{ video.title }}</h1>
<p>{{ video.description }}</p>
<p class="text-muted">投稿日:{{ video.created_at }} - 更新日:{{ video.updated_at }}</p>
<div class="embed-responsive embed-responsive-16by9">
  <!--イメージフィールド、ファイルフィールドで、ファイルの中身のデータを表示する場合は、.urlを末尾につける-->
  <video controls class="embed-responsive-item" src="{{ video.upload.url }}"></video>
</div>
{% endblock %}

videos/templates/videos/video_form.html
{% extends 'videos/base.html' %}
{% block content %}
<!--ファイルアップロードする際に、enctype=...のような記述がないとファイルが正しくアップロードされない-->
<form action="" method="POST" enctype='multipart/form-data'>
  {{ form.non_field_errors }}
  {% for field in form %}
  <div class="form-group">
    <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
    {{ field }}
    {{ field.errors }}
  </div>
  {% endfor %}
  {% csrf_token %}
  <button type="submit" class="btn btn-dark">送信</button>
</form>

{% endblock %}

videos/templates/videos/video_list.html
{% extends 'videos/base.html' %}
{% load static %}
{% block content %}
<div class="row">
  {% for video in video_list %}
  <div class="col-6 col-md-2">
    <a href="{% url 'videos:play' video.pk %}">
      {% if video.thumbnail %}
      <!--ファイルフィールドやイメージフィールドは、フィールド名.urlとすることで、そのファイルの置き場所を取得-->
      <img class="imag-thumbnail" src="{{ video.thumbnail.url }}" alt="{{ video.title }}">
      {% else %}
      <img class="img-thumbnail" src="{% static 'videos/noimage.jpg' %}" alt="{{ video.title }}">
      {% endif %}
    </a>
    <p class="text-center">{{ video.title }}</p>
  </div>
  {% endfor %}
</div>
{% endblock %}